Element_Project/src/objects/Error_Log__c.object
<CustomObject>
    <fields>
        <fullName>Class_Name__c</fullName>
        <label>Class Name</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Error_Description__c</fullName>
        <label>Error Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Line_Number__c</fullName>
        <label>Line Number</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Log_Time__c</fullName>
        <label>Log Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Method_Name__c</fullName>
        <label>Method Name</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Error_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Error_Log</label>
    <nameField>
        <displayFormat>EL-{0000}</displayFormat>
        <label>Error_Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error_Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Element_Project/src/classes/ExceptionHandler.cls
public class ExceptionHandler {
    public static void logApexCalloutError(String className,String methodName,String lineno,String errorMsg) {
        Error_Log__c log = new Error_Log__c();
        log.Class_Name__c = className;
        log.Method_Name__c = methodName;
        log.Line_Number__c = lineno;
        log.log_time__c=System.now();
        log.user__c = UserInfo.getUserId();
        
        // You can get HTTP Status Code and Response Body
        if(errorMsg!=null)
        {
            log.Error_Description__c=errorMsg;
        }
        insert log;     
    }  
}