Element_Project/src/objects/Policy__c.object
<CustomObject>
    <description>Policies Information</description>
    <fields>
        <fullName>Policy_Name__c</fullName>
        <description>Policy Name</description>
        <inlineHelpText>Enter name of the policy</inlineHelpText>
        <label>Policy Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Policy</label>
    <nameField>
        <label>Policy ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Policies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Element_Project/src/objects/Related_Policy__c.object
<CustomObject>
    <fields>
        <fullName>Case__c</fullName>
        <description>Policies related case</description>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Related Policies</relationshipLabel>
        <relationshipName>Related_Policies</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Policy_Name__c</fullName>
        <formula>Policy__r.Policy_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Policy Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Policy__c</fullName>
        <label>Policy</label>
        <referenceTo>Policy__c</referenceTo>
        <relationshipLabel>Related Policies</relationshipLabel>
        <relationshipName>Related_Policies</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Related Policy</label>
    <nameField>
        <displayFormat>Policy-{000000}</displayFormat>
        <label>Related Policies Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Related Policies</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Element_Project/src/classes/PaymentHistoryCtrl.cls
public class PaymentHistoryCtrl {
    
    @AuraEnabled
    public static string getPaymentHistory(){
        HttpResponse response = new HttpResponse ();
         try{
            Http h = new Http();
            HttpRequest req = new HttpRequest();
            req.setEndpoint(System.Label.ENDPOINT_URL);
            req.setMethod('GET');
            
            // Send HTTP Request to get Payment histories 
            response = h.send(req);
            if(response.getStatusCode()==200){
               return response.getBody();
            }
            return null;
        }
        catch(exception e){
            String responseError = 'StatusCode: '+ String.valueOf(response.getStatusCode()) + 'Response Body: '+ response.getBody();
            ExceptionHandler.logApexCalloutError('PaymentHistoryCtrl','getPaymentHistory',string.valueOf(e.getLineNumber()), responseError);
        }
        return null;
    }
    
    @AuraEnabled
    public static List<Related_Policy__c > getRelatedPolicies(Id caseId){
        try{
    		return [SELECT Id, Name, Case__c, Policy__c, Policy_Name__c FROM Related_Policy__c Where Case__c =: caseId];
        }
        catch(StringException e){
            ExceptionHandler.logApexCalloutError('PaymentHistoryCtrl','getRelatedPolicies',string.valueOf(e.getLineNumber()), e.getMessage());
        }
        catch(QueryException qe){
            ExceptionHandler.logApexCalloutError('PaymentHistoryCtrl','getRelatedPolicies',string.valueOf(qe.getLineNumber()), qe.getMessage());
        }
        return null;
    }

}