Element_Project/src/objects/Policy__c.object
<CustomObject>
    <description>Policies Information</description>
    <fields>
        <fullName>Plan_Type__c</fullName>
        <label>Plan Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Policy_Name__c</fullName>
        <description>Policy Name</description>
        <inlineHelpText>Enter name of the policy</inlineHelpText>
        <label>Policy Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Discontinued</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Policy</label>
    <nameField>
        <label>Policy ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Policies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Element_Project/src/objects/Related_Policy__c.object
<CustomObject>
    <fields>
        <fullName>Case__c</fullName>
        <description>Policies related case</description>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Related Policies</relationshipLabel>
        <relationshipName>Related_Policies</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Policy_Name__c</fullName>
        <formula>Policy__r.Policy_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Policy Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Policy__c</fullName>
        <label>Policy</label>
        <referenceTo>Policy__c</referenceTo>
        <relationshipLabel>Related Policies</relationshipLabel>
        <relationshipName>Related_Policies</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Related Policy</label>
    <nameField>
        <displayFormat>Policy-{000000}</displayFormat>
        <label>Related Policies Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Related Policies</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Element_Project/src/classes/PaymentHistoryCtrlTest.cls
@isTest
private class PaymentHistoryCtrlTest {
	
    @testSetup static void setup() {
        
        Case caseObj = new Case();
        caseObj.Status = 'New';
        caseObj.Origin = 'Email';
        caseObj.Type = 'Other';
        caseObj.Subject = 'Need Assistance on Renewal of Insurance';
        insert caseObj;
        
        Policy__c policyObj = new Policy__c();
        policyObj.Name = 'POLICY123AAB';
        policyObj.Policy_Name__c = 'LIC e term policy';
        policyObj.Plan_Type__c = 'Mid term';
        policyObj.Status__c = 'Active';
        insert policyObj;
        
        Related_Policy__c relatedPolicy = new Related_Policy__c();
        relatedPolicy.Policy__c = policyObj.Id;
        relatedPolicy.Case__c = caseObj.Id;
        insert relatedPolicy;
    }
    
    private static testMethod void getRelatedPoliciesShouldReturnPoliciesRelatedToCase() {
        Case caseObj = [Select Id FROM Case Where Status = 'New' LIMIT 1];
        
        List<Related_Policy__c> relatedPolicies = new List<Related_Policy__c>();
        Test.startTest();
        	relatedPolicies = PaymentHistoryCtrl.getRelatedPolicies(caseObj.Id);
        Test.stopTest();
        
        Related_Policy__c relatedPolicy = [Select Id, Policy__c, Case__c FROM Related_Policy__c WHERE Case__c =: caseObj.Id];
        
        System.assertNotEquals(relatedPolicies, null);
        System.assertEquals(relatedPolicies[0].Id, relatedPolicy.Id);
    }
    
    private static testmethod void getPaymentHistoryShouldGetValidResponseWhenSendingValidHttpRequest() {
        PaymentHistoryMock fakeResponse = new PaymentHistoryMock(200,
                                                               'Complete',
                                                               '[{"Name": "sForceTest1"}]'
                                                               );
        Test.setMock(HttpCalloutMock.class, fakeResponse);
        Test.startTest();
        	PaymentHistoryCtrl.getPaymentHistory();
        Test.stopTest();
    }
    
    private static testmethod void getPaymentHistoryShouldGetInvalidResponseWhenSendingInvalidHttpRequest() {
        PaymentHistoryMock fakeResponse = new PaymentHistoryMock(400,
                                                               'Bad Request',
                                                               '[]'
                                                               );
        Test.setMock(HttpCalloutMock.class, fakeResponse);
        PaymentHistoryCtrl.getPaymentHistory();
    }
}